"""Add session id to conversations

Revision ID: bae7a6edcfb4
Revises: fe1884c5341c
Create Date: 2026-07-05 13:14:49.958394

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bae7a6edcfb4'
down_revision: Union[str, Sequence[str], None] = 'fe1884c5341c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("conversations", sa.Column("session_id", sa.String(), nullable=True))
    op.execute("UPDATE conversations SET session_id = title WHERE session_id IS NULL")
    op.alter_column("conversations", "session_id", nullable=False)
    op.create_index(op.f('ix_conversations_session_id'), 'conversations', ['session_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_conversations_session_id'), table_name='conversations')
    op.drop_column('conversations', 'session_id')
    # ### end Alembic commands ###
